#!/bin/bash
set -e
linkdirs=( ".config/awesome" ".urxvt" ".config/i3" )
copydirs=( "etc/udev/rules.d" "etc/systemd/system" )
cleanuppath() {
    if test -L "$1"; then
        rm "$1"
    elif test -e "$1"; then
        rm "$1"
    fi
}

islinkdir() {
    for linkdir in "${linkdirs[@]}"; do
        if [[ "$file" == $linkdir ]]; then
            return 0
        fi
    done
    return 1
}

join_by() {
    local IFS="$1"; shift; echo "$*";
}

linkfile() {
    cmd="ln -s"
    sourcepath="$1"
    target="$2"
    file="$3"
    fullpath="$1/$file"
    targetpath="$target/$file"
    cleanuppath "$targetpath"
    for copydir in "${copydirs[@]}"; do
        if [[ "$file" == $copydir* ]]; then
            cmd="cp"
            break
        fi
    done
    $cmd "$fullpath" "$target/$file"
}

linkfiles() {
    if ! test -e $1; then
        echo "Source $1 does not exists"
        return
    fi
    target="$2"
    pushd "$1" > /dev/null 
    for file in $(find -type d -printf '%P\n'); do
        if ! islinkdir $file; then
            mkdir -p "$target/$file"
        fi
    done
    skipme=$(join_by \| "${linkdirs[@]}")
    for file in $(find -type f -printf '%P\n' | grep -E -v "($skipme)"); do
        linkfile "$1" "$target" "$file"
    done
    for linkdir in "${linkdirs[@]}"; do
        if ! test -e "$linkdir"; then
            echo "Dir $linkdir does not exists skipping"
            continue
        fi
        linkfile "$1" "$target" "$linkdir"
    done
    popd > /dev/null
}


ROOT=""
scripdir="$(dirname $(readlink -f "$0"))"
if [ "$1" == "--root" ]; then
    if [ "$UID" != "0" ]; then
        echo "--root requires you to be root"
        exit 1
    fi
    linkfiles "${scripdir}/osconfig" "/"
    linkfiles "${scripdir}/overlay/osconfig" "/"
else
    linkfiles "${scripdir}/homeconfig" "$HOME"
    linkfiles "${scripdir}/overlay/homeconfig" "$HOME"
fi

