source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/fzf.kak"

hook global BufWritePost .* %{
    git show-diff
}
hook global BufOpenFile .* %{
    git show-diff
}

hook global InsertCompletionShow .* %{
    try %{
        #this command temporarily removes cursors preceded by whitespace;
        #if there are no cursors left, it raises an error, does not
        #continue to execute the mapping commands, and the error is eaten
        #by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

hook global InsertChar \t %{
      exec -draft h@
}

map global insert <s-tab> '<a-;><lt>'

hook global InsertChar \t %{
    exec -draft h@
}


alias global x write-quit
alias global vsplit tmux-new-horizontal
set-option global tabstop 4
set-option global indentwidth 4
map global normal <c-p> ': fzf-mode<ret>'
map global user n ":ranger-currentfile<ret>"
map global user s ":tmux-new-horizontal<ret>"
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'
colorscheme solarized-dark
set-option global fzf_file_command 'ag --hidden --ignore .git -g ""'
set-option global fzf_highlighter 'bat'
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
lsp-auto-hover-enable
map global normal <c-l> ': enter-user-mode lsp<ret>'
