#! /bin/zsh

bindkey "^[[3~" delete-char
bindkey "^[[5~" backward-word
bindkey "^[[6~" forward-word

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

case $TERM in
rxvt)
    bindkey '\e[7~' beginning-of-line # Home
    bindkey '\e[8~' end-of-line # End
    ;;
xterm)
    bindkey '\e[H' beginning-of-line # Home
    bindkey '\e[F' end-of-line # End
    ;;
linux)
    bindkey '\e[1~' beginning-of-line # Home
    bindkey '\e[4~' end-of-line # End
    ;;
*)
    ;;
esac

bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^K" kill-line
bindkey "^L" clear-screen
bindkey "^R" history-incremental-search-backward
bindkey "^U" kill-whole-line
bindkey "^V" quoted-insert
bindkey "^W" backward-kill-word

bindkey "^N" down-history
bindkey "^P" up-history

bindkey "^[H" run-help
bindkey "^[h" run-help

