#!/bin/zsh

function hgp(){
    sed -i "s/pretxncommit.pyflakes/#pretxncommit.pyflakes/" ~/.hgrc
    hg $*
    exitcode=$?
    sed -i "s/#pretxncommit.pyflakes/pretxncommit.pyflakes/" ~/.hgrc
    return $exitcode
    
}

function hga() {
    for x in `ls`; do
        pushd $x
        if [ -e ".hg" ]; then
            echo "Repo $x"
            hgp $*
        fi
        popd
    done
}

function hgr() {
    local hgroot=$(hg root)
    hgp commit -l "${hgroot}/.hg/last-message.txt" $*
}
