#!/bin/zsh

autoload zmv
alias mmv='noglob zmv -W'

# For giggles
alias du="du -hcs"
alias df="df -h"

alias ls="ls --color=auto"
alias la="ls --color=always -a"
alias ll="ls --color=always -l"
alias lla="ls --color=always -la"
alias lal="ls --color=always -la"

# cd stuff
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."

alias cdr="cd \$vcs_info_msg_1_"

alias tmux="tmux -2"

#rsa stuff
alias ssh="loadrsa; ssh"
alias scp="loadrsa; scp"
alias scpresume="loadrsa; rsync -Pazhv"
alias git="loadrsa; git"
alias hg="loadrsa; hg"
alias mosh="mosh --predict=experimental"
alias wget="wget --content-disposition"

alias grep="grep --colour=auto"

vik(){
       sed -i $1d ~/.ssh/known_hosts
}


ssh2(){
    ip=$1
    shift;
    pubkey=$(cat ~/.ssh/id_rsa.pub)
    /usr/bin/ssh $ip "
    if [ ! -e ~/.ssh ]; then
        mkdir ~/.ssh
    fi
    if ! grep \"$pubkey\" ~/.ssh/authorized_keys > /dev/null; then
        echo \"$pubkey\" >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
    fi
    "
    /usr/bin/ssh $ip $@
}

sshr() {
    ssh -O exit $@
    ssh $@
}

mosh2() {
    ssh2 $1 "apt-get install -y mosh"
    mosh $1
}

loadkey(){
    eval `keychain -q --eval --agents ssh id_rsa`
}

function v(){
    vimbin="vim"
    if [ -z "$@" ] ; then
        $vimbin -c "normal '0";
        return 0;
    fi
    array=("${(s/:/)@}")
    if [ ! -e "${array[1]}" ]; then
        array[1]=$(which ${array[1]})
    fi
    if [ -z "${array[2]}" ]; then
        array[2]="0"
    fi
    $vimbin "${array[1]}" "+${array[2]}"
}

function cd() {
    local cdto="BKMRK_${1}"
    cdto="${(P)cdto}"
    if [ -n "$cdto" -a ! -e "${1}" ]; then
        local extra=`echo "$1" | cut -d / -f 2-`
        if [ "$extra" = "$1" ]; then
            extra=""
        fi
        builtin cd "$cdto/$extra"
        return
    fi
    builtin cd $*
}

function yaourt(){
    /usr/bin/yaourt $*
    hash -r
}

function apt-get(){
    /usr/bin/apt-get $*
    hash -r
}

function zfload(){
    autoload -U zfinit
    zfinit
    cmd="zf$1"
    shift
    $cmd $*
}

function ownedby(){
    if [ -e "$*" ]; then
        filename="$*"
    else
        filename=$(which "$*")
    fi
    yaourt -Qo $filename
}

function countdown(){
   date1=$((`date +%s` + $1)); 
   while [ "$date1" -ge `date +%s` ]; do 
     echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
     sleep 0.1
   done
}
function stopwatch(){
  date1=`date +%s`; 
   while true; do 
    echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r"; 
    sleep 0.1
   done
}
