export PYTHONPATH=$HOME/work/pythonenv
export I3SOCK=/run/user/1000/i3/ctrl.socket
export GOPATH=$HOME/Dev/go
export PATH=$HOME/mygit/scripts/bin:$HOME/bin:$GOPATH/bin:$PATH
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export XDG_CURRENT_DESKTOP=gnome
export QT_GRAPHICSSYSTEM=native
export _JAVA_AWT_WM_NONREPARENTING=1
export LANG="en_US.utf8"
export LC_TIME="en_GB.utf8"
unset LC_ALL
